version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: air cmd/server/main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}

volumes:
    postgres-data:
